version: '3.8'

services:

  nginx:
    image: nginx:1.25.2
    ports:
        - "80:80"
        - "8000:8000"
    volumes:
        - ./nginx_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - assignment_network
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      - assignment_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - assignment_network

networks:
  assignment_network:
    name: assignment_network
