name: Backup Prod Database

on:
    schedule:
        # Cada 10 dias se ejecuta un backup
        - cron: '0 0 */10 * *'
    workflow_dispatch:


jobs:
    # Primero definimos la fecha de hoy

    determine_date:
        runs-on: ubuntu-latest
        outputs:
            today: ${{ steps.get-date.outputs.date }}
        steps:
            - name: Get current date
              id: get-date
              shell: bash
              run: echo "date=$(date +'%d-%m-%Y')" >> "$GITHUB_OUTPUT"

    backup_db:
        runs-on: ubuntu-latest
        env:
            TODAY: ${{ needs.determine_date.outputs.today }}
        needs: determine_date
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Postgres Dump Backup
              uses: tj-actions/pg-dump@v3
              with:
                database_url: "${{ secrets.DB_URL}}"
                postgresql_version: "15"
                path: "db-prod-${{ env.TODAY }}.bak" 
                options: "-O"
            - name: Upload Backup Artifact
              uses: actions/upload-artifact@v4
              with:
               name: db-prod-${{ env.TODAY }}
               path: "db-prod-${{ env.TODAY }}.bak" 
               retention-days: 1

    # Despues bajo el backup y lo subo a Azure
    upload_azure_blob:
        name: Upload to Azure Blob
        runs-on: ubuntu-latest
        env:
            TODAY: ${{ needs.determine_date.outputs.today }}
        needs: [determine_date, backup_db]
        steps:
            - name: Download Backup File
              uses: actions/download-artifact@v4
              with:
                name: db-prod-${{ env.TODAY }}
                path: "db-prod-${{ env.TODAY }}.bak" 
            
            - name: Upload To Azure Blob Storage
              uses: azure/cli@v2
              with:
                inlineScript: |
                    az storage blob upload --file db-prod-${{ env.TODAY }}.bak --blob-url https://fiubastorage.blob.core.windows.net/backups-db --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}



    
    
 

