name: Main CI/CD
on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: 'token from codecov page' 
        required: true
      AZURE_STORAGE_CONNECTION_STRING:
        description: 'connection string from azure page' 
        required: true
      AZURE_STORAGE_CONTAINER_NAME:
        description: 'container name from azure page' 
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  unit_test:
    needs: build
    uses: ./.github/workflows/tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration:
    needs: build
    uses: ./.github/workflows/integration.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
