name: Pull Request Github Workflow
run-name: PR created by @${{ github.actor }} for ${{ github.event.pull_request.head.ref }} 
on:
    pull_request:
      types: [opened, synchronize, reopened ]
    workflow_dispatch:
        

jobs:
    check_branches:
      runs-on: ubuntu-latest
      steps: 
        - name: PR branches validation
          run: |
            if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" == feat/assignment-* ]]; then
              echo "Branches are correct"
              exit 0
            else
              echo "Error: Branch names are not correct."
              exit 1
            fi     
    build:
      needs: [check_branches]
      uses: ./.github/workflows/main.yml
      secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

