name: PR Continuos Integration
on:
    pull_request:
      types: [opened]
    workflow_dispatch:

jobs:
    check_branches:
      if: ${{ ! (contains(github.event.pull_request.base.ref, 'main') && startsWith(github.event.pull_request.head.ref, 'feat/')) }}
      runs-on: ubuntu-latest
      steps: 
        - name: PR branches validation failed
          run: |
            echo "Branches are NOT correct. Base branch should be 'main' and head branch should start with 'feat/'"
            exit 1     
    ci:
      needs: [check_branches]
      uses: ./.github/workflows/ci.yml
      secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    performance:
      needs: [check_branches]
      uses: ./.github/workflows/integration.yml
      secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

