name: PR Continuos Integration
on:
    pull_request:
      types: [opened]
    workflow_dispatch:

jobs:
    check_branches:
      runs-on: ubuntu-latest
      steps: 
        - name: PR branches validation
          run: |
            if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" == feat/assignment-* ]]; then
              echo "Branches are correct"
              exit 0
            else
              echo "Error: Branch names are not correct."
              exit 1
            fi     
    ci:
      needs: [check_branches]
      uses: ./.github/workflows/ci.yml
      secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    performance:
      needs: [check_branches]
      uses: ./.github/workflows/integration.yml
      secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

