name: Run Unit Tests
run-name: Unit test workflow triggered by @${{ github.actor }}
on: [push, workflow_call]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: ./.github/actions/build
        - name: Run the automated tests
          run: poetry run pytest 
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}