name: Unit testing in Python
run-name: Unit test excecution by @${{ github.actor }}
on: workflow_call

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Build
          uses: ./.github\workflows\build.yml
        - name: Run the automated tests
          run: poetry run pytest 
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}